version: '2'
services:
  web:
    image: 911582809631.dkr.ecr.eu-west-1.amazonaws.com/mapsurvey:latest
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 80:8000
    env_file:
      - ./.env.prod
    links:
      - db
    cpu_shares: 100
    mem_limit: 262144000

  db:
    image: postgis/postgis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env.prod.db
volumes:
  postgres-data:

