"""Resolve a `Question.icon_class` value to something drawable.

Two value forms exist:

* a Font Awesome class list — `fas fa-bus`, `far fa-circle`, legacy `fa fa-bus` — rendered
  as `<i class="…">`;
* `<set>:<name>` — `maki:bus`, `temaki:bench` — rendered as an SVG `<use>` of symbol
  `<set>-<name>` from that set's sprite sheet.

Every surface that draws a marker icon goes through `resolve()` (or the `marker_icon`
template tag, or `MarkerIcon` in the browser) so no template ever puts a `maki:` value into
a `class` attribute. A Font Awesome-shaped value passes through untouched even when the
catalog has never heard of it, which is what keeps old rows and pasted classes rendering as
they always did; an unknown SVG name falls back to the default pin because a blank glyph
on a coloured pin is the failure the resolver exists to prevent.

The catalog itself is generated by `scripts/build_icon_catalog.py`; see its docstring.
"""
import json
import os
import re
from functools import lru_cache

from django.templatetags.static import static
from django.utils.html import format_html

CATALOG_PATH = os.path.join(os.path.dirname(__file__), 'assets', 'data', 'icon_catalog.json')
CATALOG_STATIC_PATH = 'data/icon_catalog.json'

SVG_SETS = ('maki', 'temaki')
SPRITE_STATIC_PATHS = {name: 'img/%s.svg' % name for name in SVG_SETS}

DEFAULT_PIN = 'fas fa-map-marker-alt'

FONT_CLASS_RE = re.compile(r'^(fas|far|fab|fa) fa-[a-z0-9-]+$')
SVG_VALUE_RE = re.compile(r'^(maki|temaki):([a-z0-9][a-z0-9_-]*)$')


@lru_cache(maxsize=1)
def catalog():
    with open(CATALOG_PATH, encoding='utf-8') as fh:
        return json.load(fh)


@lru_cache(maxsize=1)
def _known_values():
    return frozenset(icon['v'] for icon in catalog()['icons'])


def is_font_class(value):
    return bool(value) and FONT_CLASS_RE.match(value.strip()) is not None


def is_svg_value(value):
    return bool(value) and SVG_VALUE_RE.match(value.strip()) is not None


def is_known(value):
    """True for a catalogued value of either form."""
    return bool(value) and value.strip() in _known_values()


def is_valid(value):
    """What the editor accepts: empty, any Font Awesome-shaped class, or a catalogued SVG name.

    Font Awesome is regex-only on purpose — old rows hold v4 `fa fa-x` names and creators
    paste Pro classes, and rejecting those on an unrelated save would be a regression.
    """
    if not value or not value.strip():
        return True
    value = value.strip()
    if is_font_class(value):
        return True
    return is_svg_value(value) and value in _known_values()


def resolve(value):
    """`{"kind": "font", "classes": ...}` or `{"kind": "svg", "set": ..., "symbol": ...}`."""
    value = (value or '').strip()
    match = SVG_VALUE_RE.match(value)
    if match:
        if value in _known_values():
            set_name, name = match.groups()
            return {'kind': 'svg', 'set': set_name, 'symbol': '%s-%s' % (set_name, name)}
        return {'kind': 'font', 'classes': DEFAULT_PIN}
    return {'kind': 'font', 'classes': value or DEFAULT_PIN}


def sprite_urls():
    """Hashed static URLs of the sprite sheets, for the browser resolver."""
    return {name: static(path) for name, path in SPRITE_STATIC_PATHS.items()}


def render(value, color=None, css_class='', style=''):
    """Markup for one icon: `<i>` for a font glyph, `<svg><use>` for a sprite symbol.

    `color` becomes the glyph colour either way (`color:` on the `<i>`, `fill:` on the
    `<svg>`); `style` is appended verbatim for surfaces that size the glyph inline.
    """
    resolved = resolve(value)
    color_css = 'color:%s;' % color if color else ''
    if resolved['kind'] == 'svg':
        fill_css = 'fill:%s;' % color if color else 'fill:currentColor;'
        href = '%s#%s' % (static(SPRITE_STATIC_PATHS[resolved['set']]), resolved['symbol'])
        return format_html(
            '<svg class="marker-icon-svg-glyph {}" style="{}{}" aria-hidden="true" focusable="false">'
            '<use href="{}"></use></svg>',
            css_class, fill_css, style, href,
        )
    return format_html(
        '<i class="{} {}" style="{}{}" aria-hidden="true"></i>',
        resolved['classes'], css_class, color_css, style,
    )
