"""
Django settings for mapsurvey project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from mapsurvey.media_prefixes import media_locations, namespace_from_env

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if load_dotenv:
    load_dotenv(Path(BASE_DIR) / '.env')

SECRET_KEY = os.environ.get("SECRET_KEY", 'secret')

DEBUG = int(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", 'localhost').split(" ")

# Add Render external hostname if set
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF trusted origins (build from ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host and host != 'localhost']

# Analytics: max client-side tracking events per survey session per hour
TRACK_EVENT_RATE_LIMIT = int(os.environ.get("TRACK_EVENT_RATE_LIMIT", 120))

# Shared secret for the /internal/purge-trash/ endpoint (curl-based cron).
# Empty string disables the endpoint entirely.
PURGE_TASK_TOKEN = os.environ.get("PURGE_TASK_TOKEN", "")

# Application definition

INSTALLED_APPS = [
    'leaflet',
    'django.contrib.gis',
    'survey.apps.SurveyConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'django_registration',
    'storages',
    'newsletter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'survey.middleware.CloudflareIPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # After auth so exceptions carry the signed-in creator's pk as distinct id.
    # Captures view exceptions to PostHog error tracking (process_exception);
    # inert when POSTHOG_PROJECT_KEY is unset -- see survey.apps.SurveyConfig.
    'posthog.integrations.django.PosthogContextMiddleware',
    'survey.middleware.LastActivityMiddleware',
    # After auth (it needs request.user) and deliberately not before Locale:
    # it writes the language COOKIE, which LocaleMiddleware reads on the NEXT
    # request. Reading the preference in time for this request is impossible --
    # LocaleMiddleware resolves the language before request.user exists.
    'survey.middleware.CreatorLanguageCookieMiddleware',
    # Applies the noindex flag survey.access_control sets. Must sit outside the
    # view so it also reaches the redirects survey_header returns.
    'survey.middleware.SurveyIndexingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'survey.middleware.ActiveOrgMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# LastActivityMiddleware writes UserActivity at most once per user per this many
# seconds (cache-gated) so activity tracking never becomes a write-per-request.
LAST_ACTIVITY_THROTTLE_SECONDS = int(os.environ.get('LAST_ACTIVITY_THROTTLE_SECONDS', 300))

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'mapsurvey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'survey.context_processors.mapbox',
                'survey.context_processors.contact',
                'survey.context_processors.active_org',
                'survey.context_processors.analytics',
                'survey.context_processors.mobile_adaptive',
            ],
        },
    },
]

WSGI_APPLICATION = 'mapsurvey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Persistent DB connections: without CONN_MAX_AGE every request forks a fresh
# Postgres backend, and on the 0.1-vCPU basic-256mb instance that fork churn is
# the dominant DB cost once gunicorn serves requests concurrently (load test
# pegged DB CPU at its cap while the web instance idled). Each gunicorn thread
# holds one connection: 2 workers x 4 threads = 8.
DB_CONN_MAX_AGE = int(os.environ.get("DB_CONN_MAX_AGE", "300"))

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
        "CONN_MAX_AGE": DB_CONN_MAX_AGE,
        "CONN_HEALTH_CHECKS": True,
    }
}

# Override with DATABASE_URL if set (for Render)
if os.environ.get("DATABASE_URL"):
    db_url = urlparse(os.environ.get("DATABASE_URL"))
    DATABASES["default"] = {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": db_url.path[1:],
        "USER": db_url.username,
        "PASSWORD": db_url.password,
        "HOST": db_url.hostname,
        "PORT": db_url.port or 5432,
        "CONN_MAX_AGE": DB_CONN_MAX_AGE,
        "CONN_HEALTH_CHECKS": True,
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

# Only minimum length is enforced. Everything else — common passwords, reuse of
# personal information, all-numeric — is surfaced as advice on the registration
# form (see survey/password_rules.py) and does not block a signup.
#
# The deliberate trade-off: NIST SP 800-63B states the compromised-password
# check as a SHALL, so a security questionnaire asking "do you reject known
# breached passwords?" gets a "no, we warn" from us. That was accepted on
# 2026-08-17, after a validator rejection cost a real signup — the person hit
# UserAttributeSimilarityValidator (Django's SequenceMatcher at 0.7 against the
# email, which is not what NIST asks for) and left. Revisit if an enterprise
# deal turns on that questionnaire line: re-adding CommonPasswordValidator here
# is a one-line change and the checklist follows automatically.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

# Creator interface languages (openspec: creator-ui-localization). Chosen from
# creator counts in production rather than market size: en 66, id 30, es 15,
# fr 12, de 9, pt 7, pl 6 — ~97% of real creators. `id` stays despite arriving
# as a single May-2026 course cohort, because cohort channels recur.
#
# This is NOT the survey-content language list: creators pick from 75 languages
# for their own question text, which is a separate system entirely (see
# survey-content-translation). Each name is written in its own language — it is
# read by someone who may not be reading English comfortably.
#
# A language listed here with an empty catalog falls back to English per string,
# which is why the marketing pages (deferred) stay English while the editor is
# translated.
# A language is listed here only once its catalog is COMPLETE. A half-filled
# catalog falls back per string, so offering it would hand the creator an
# English interface sprinkled with their own language — worse than English,
# and worse than not offering it. Catalogs for ru/es/fr/pt/pl/id exist in the
# repo and are being filled; each joins this list when it is done. `pt` is
# European Portuguese (inquérito / utilizador / ficheiro / ecrã): the traffic
# is Portuguese, not Brazilian. A Brazilian audience would get its own `pt-BR`
# catalog rather than edits to this one.
#
# Narrowing this list does NOT affect respondents: their chrome is activated
# per survey with `translation.activate()`, which resolves against the catalog
# on disk and ignores LANGUAGES entirely — verified across all 75 locales.
LANGUAGES = [
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('fr', 'Français'),
    ('es', 'Español'),
    ('pt', 'Português'),
    ('pl', 'Polski'),
    ('id', 'Bahasa Indonesia'),
    ('nl', 'Nederlands'),
    ('it', 'Italiano'),
    ('fi', 'Suomi'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'survey', 'locale'),
]

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/' # URL для медии в шаблонах

STATIC_ROOT = os.path.join(BASE_DIR, "survey/static")
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'survey/assets'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# STATIC FILES
#
# Static never moves to object storage. Manifest storage fingerprints filenames
# with a content hash, so WhiteNoise serves hashed assets with far-future
# immutable Cache-Control and Cloudflare's edge can cache them for a year.
# Deploys bust caches by hash. Side effect: collectstatic fails on dangling
# static references (surfaces at deploy, not at runtime).
STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
_STATICFILES_BACKEND = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA FILES
#
# Uploaded media does have to leave the instance filesystem: a Render disk
# attaches to one instance at a time, which is what rules out zero-downtime
# deploys and pins the web service to a single instance.
USE_S3 = os.getenv('USE_S3') == 'TRUE'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-southeast-2')

    # Buckets created since April 2023 default to Object Ownership =
    # BucketOwnerEnforced, which disables ACLs outright — sending one fails the
    # upload with AccessControlListNotSupported. Public read comes from the
    # bucket policy instead, so no object may carry an ACL.
    AWS_DEFAULT_ACL = None

    # The domain must carry the Region. The legacy global form
    # ({bucket}.s3.amazonaws.com) answers 307 for a bucket outside us-east-1:
    # browsers follow the redirect, boto3 does not for every verb, and every
    # viewer pays an extra round trip to Virginia first.
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    # Sign with SigV4 against the bucket's own Region. Without both of these,
    # boto3 falls back to the deprecated SigV2 scheme on the legacy global
    # endpoint — which is the same region-less host that answers 307, only now
    # on the URLs that respondents' private files depend on.
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'virtual'

    # Lifetime of a signed link to a private object. Short enough that a leaked
    # URL stops working quickly, long enough to survive a slow page load.
    AWS_QUERYSTRING_EXPIRE = int(os.getenv('AWS_QUERYSTRING_EXPIRE', '900'))

    # Each environment writes under its own namespace, so a PR preview cannot
    # address — let alone overwrite — a production key. Production keeps the
    # bare prefixes, which is where the relative paths already in the database
    # resolve, so the move needs no data rewrite.
    MEDIA_S3_NAMESPACE = namespace_from_env(os.environ)

    # Two tiers, and the split matters. Creator artwork is public — it is
    # already on display on every survey and public results page. Respondent
    # submissions are private and reachable only through a signed URL: a link
    # is not an access control, and links leak into logs, Referer headers,
    # exported archives and screenshots.
    PUBLIC_MEDIA_LOCATION, PRIVATE_MEDIA_LOCATION = media_locations(MEDIA_S3_NAMESPACE)

    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'

    STORAGES = {
        'default': {'BACKEND': 'survey.storage_backends.PublicMediaStorage'},
        'staticfiles': {'BACKEND': _STATICFILES_BACKEND},
    }

else:
    MEDIA_URL = '/mediafiles/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': _STATICFILES_BACKEND},
    }

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'survey/assets'),)




INTERNAL_IPS = ('127.0.0.1',)

LOGIN_REDIRECT_URL = '/editor/'
# Skip the "Signed Out" confirmation page — LogoutView redirects straight home.
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_ACTIVATION_DAYS = int(os.environ.get('ACCOUNT_ACTIVATION_DAYS', 7))

# Mapbox
MAPBOX_URL = os.environ.get('MAPBOX_URL', 'https://api.mapbox.com/styles/v1/mapbox/streets-v12/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}')
MAPBOX_ACCESS_TOKEN = os.environ.get('MAPBOX_ACCESS_TOKEN', '')

# Email backend
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
AUTH_USER_EMAIL_UNIQUE = True

AUTHENTICATION_BACKENDS = [
    'survey.backends.EmailOrUsernameBackend',
]
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() in ('true', '1')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@mapsurvey.org')

# Plausible Analytics
PLAUSIBLE_SCRIPT_URL = os.environ.get('PLAUSIBLE_SCRIPT_URL', '')
# Google Search Console verification token (meta-tag method); empty = tag not rendered.
GOOGLE_SITE_VERIFICATION = os.environ.get('GOOGLE_SITE_VERIFICATION', '')

# Internal product analytics (PostHog). Empty key = no snippet at all, which is what
# keeps local development, the test suite and PR previews out of the production project.
# Cloud EU by default: production runs in Render's Oregon region, and pointing analytics
# at the US too would add a second US processor to a stack whose data residency is already
# the recurring objection in European public-sector conversations.
POSTHOG_PROJECT_KEY = os.environ.get('POSTHOG_PROJECT_KEY', '')
# `or` rather than a get() default: render.yaml declares this as `sync: false`, so the
# dashboard can hand us an empty string, and an empty api_host initialises the SDK
# against nothing at all -- a silent no-op that looks exactly like working analytics.
POSTHOG_API_HOST = os.environ.get('POSTHOG_API_HOST') or 'https://eu.i.posthog.com'
# Where the *browser* sends events, which is a different question from where the server
# sends them. `eu.i.posthog.com` is on every mainstream blocklist, and the audience of our
# creator-facing pages -- planners, GIS analysts, researchers -- runs blockers more than
# most, so the events we lose are biased rather than random. Pointing the snippet at a
# first-party hostname (a PostHog-managed reverse proxy, CNAME'd from our own domain)
# leaves blocklists nothing to match.
#
# The server-side client deliberately does NOT use this: see survey/apps.py. Ad blockers
# do not exist inside our containers, so proxying error capture would add a DNS record and
# a CDN edge to the one subsystem whose job is to keep working when things are broken.
#
# Empty = identical to the behaviour before the proxy existed, which is what keeps local
# development, the test suite and PR previews out of it. The fall-back to POSTHOG_API_HOST
# lives in `survey.context_processors.analytics`, not here: resolving it at import time
# would freeze whatever POSTHOG_API_HOST was then, so overriding the API host afterwards
# (tests, a preview pointed at another project) would silently leave the browser on the
# old one.
POSTHOG_CLIENT_HOST = os.environ.get('POSTHOG_CLIENT_HOST', '')
# Session replay of the editor, off unless explicitly switched on. Two reasons this is a
# setting rather than a constant in the template:
#
# 1. The emergency stop must not need a deploy. A mounted disk pins us to one instance and
#    rules out zero-downtime deploys, so "turn recording off right now" has to be an
#    environment change, not a release.
# 2. This repository is public. A fork or a self-hosted install must not inherit our
#    recording posture from our source; they get the same default as local development.
#
# What is recorded is bounded in three places, and only the first is here: the snippet
# masks every input before anything leaves the browser (see _analytics.html), the snippet
# is absent on respondent surfaces (POSTHOG_EXCLUDED_PREFIXES), and a URL trigger in the
# PostHog project keeps recording to /editor/ so anonymous marketing visitors are left
# alone. The respondent boundary is the second one, never the trigger.
POSTHOG_SESSION_REPLAY = os.environ.get('POSTHOG_SESSION_REPLAY', 'False').lower() in ('true', '1')
# Surfaces PostHog must never load on. Both belong to somebody else's audience:
# `/surveys/` is a customer's respondents, `/r/` is a customer's public readers. Measuring
# them is not our business -- it is a feature we sell, served by `SurveyEvent` out of our
# own database (`survey/events.py`) -- and this list is what keeps the /trust/ promise that
# the survey-taking flow carries no third-party scripts literally true.
# Enforced in `survey.context_processors.analytics` rather than by omitting the include from
# `base_survey_template.html`, so a base template added later inherits the exclusion instead
# of depending on which existing one its author happened to copy.
POSTHOG_EXCLUDED_PREFIXES = ('/surveys/', '/r/')

# The same boundary, for respondent surfaces the prefix list cannot reach. The editor's Live
# preview panel frames a real respondent page served from under `/editor/`, so its snippet used
# to run a second PostHog client in the creator's tab: one session carrying two recorders and
# two viewports (session replay alternated between the iframe's ~470px and the editor's ~1600px),
# and every preview refresh counted as an editor page view.
#
# Keyed on the resolved view name rather than a path pattern because `preview` is not a reserved
# segment: `/editor/surveys/<uuid>/public-results/preview/` is a different surface that renders a
# standalone template and was never affected. Renaming a view here without updating this tuple
# restores the bug silently -- the tests reverse both URLs by name so that fails the suite.
POSTHOG_EXCLUDED_VIEW_NAMES = ('editor_section_preview', 'editor_survey_thanks_preview')

# --- Server-side error capture (PosthogContextMiddleware) ---
# The middleware's process_exception reports view exceptions to PostHog error tracking.
# Client setup (and the "empty key = disabled" gate) lives in survey.apps.SurveyConfig.


# Without a key the middleware must not even try: posthog's lazy setup() raises
# ValueError("API key is required") before it ever looks at the `disabled` flag,
# so an unconfigured deployment would have the error reporter break the very
# error handling it exists to observe. Found by the full suite -- 17 tests that
# raise on purpose died inside the reporter.
POSTHOG_MW_CAPTURE_EXCEPTIONS = bool(POSTHOG_PROJECT_KEY)


# Substrings that mark a user-agent as an automated client. Lowercase; matched
# case-insensitively. 'bot' alone covers Googlebot, bingbot, PetalBot, AhrefsBot
# and most of the long tail. The check lives in the request filter and NOT in a
# before_send hook because on respondent surfaces `_posthog_scrub_tags` removes
# `$user_agent` before capture -- downstream there is nothing left to classify.
POSTHOG_BOT_UA_MARKERS = (
    'bot', 'crawl', 'spider', 'slurp', 'preview', 'headless',
    'python-requests', 'python-httpx', 'aiohttp', 'curl/', 'wget/',
    'scrapy', 'go-http-client', 'okhttp', 'java/', 'libwww',
)


def _posthog_skip_request(request):
    # Admin stack traces routinely embed object reprs; the debug toolbar is noise.
    # Respondent paths are deliberately NOT skipped -- a 500 on /surveys/ is our
    # defect -- their events are scrubbed by _posthog_scrub_tags instead.
    #
    # Bot requests ARE skipped, exceptions included. Crawlers re-walking dead
    # draft-survey URLs made the top error-tracking issue read as "58 affected
    # users" when 78 of 82 hits in the request log were bot user-agents
    # (audited 2026-08-21). A defect only bots can trigger is indistinguishable
    # from that noise, so their exceptions are not worth the signal they cost.
    # An absent User-Agent counts as a bot: browsers always send one.
    #
    # Reads the key through django.conf.settings rather than the module-level
    # name so `override_settings` actually changes the behaviour under test; a
    # closure over the module global is invisible to it and would let this
    # function be "tested" without ever exercising the configured branch.
    from django.conf import settings as configured

    if not getattr(configured, 'POSTHOG_PROJECT_KEY', ''):
        return False
    user_agent = request.META.get('HTTP_USER_AGENT', '').lower()
    if not user_agent or any(marker in user_agent for marker in POSTHOG_BOT_UA_MARKERS):
        return False
    return not request.path.startswith(('/admin/', '/__debug__/'))


# The exact tag names the SDK's middleware emits. Spelled out here because
# getting one wrong fails silently in the worst direction: `$ip_address` was
# briefly written as `$ip`, which pops nothing, so a respondent's IP would have
# been transmitted from behind Cloudflare (which always sets X-Forwarded-For).
# `PostHogErrorTrackingTest.test_sdk_tag_names_are_what_we_scrub` pins these
# against the installed SDK so a rename breaks the suite instead of leaking.
POSTHOG_RESPONDENT_IDENTIFYING_TAGS = ('$ip_address', '$user_agent')


def _posthog_scrub_tags(tags):
    """Strip respondent-describing metadata from events on excluded surfaces.

    Errors there are still ours to see, but the request metadata describes a
    respondent: their IP, their browser, and a URL that names which survey they
    were answering. Keep the exception, drop the description.
    """
    path = tags.get('$request_path') or ''
    for prefix in POSTHOG_EXCLUDED_PREFIXES:
        if path.startswith(prefix):
            for tag_name in POSTHOG_RESPONDENT_IDENTIFYING_TAGS:
                tags.pop(tag_name, None)
            tags['$request_path'] = prefix
            if '$current_url' in tags:
                tags['$current_url'] = prefix
            break
    return tags


POSTHOG_MW_REQUEST_FILTER = _posthog_skip_request
POSTHOG_MW_TAG_MAP = _posthog_scrub_tags

# Acquisition metrics sync (top of the creator funnel).
# Every credential below defaults to empty: unset means "not configured", which the
# funnel dashboard renders as such instead of as a zero.
GSC_SITE = os.environ.get('GSC_SITE', 'sc-domain:mapsurvey.org')
# Service-account key as JSON in the environment (production; Render has no secret files).
GSC_SERVICE_ACCOUNT_JSON = os.environ.get('GSC_SERVICE_ACCOUNT_JSON', '')
# Local-development fallback: the same key as a file on disk. No default path -- this
# repository is public, and a hardcoded path would publish the GCP project and key
# filename for no benefit. Set GSC_KEY in your (gitignored) .env instead.
GSC_KEY_PATH = os.path.expanduser(os.environ.get('GSC_KEY', ''))
PLAUSIBLE_API_KEY = os.environ.get('PLAUSIBLE_API_KEY', '')
PLAUSIBLE_SITE_ID = os.environ.get('PLAUSIBLE_SITE_ID', 'mapsurvey.org')

# What the "marketing pages" GSC segment excludes. Defined by exclusion because the
# set of app prefixes is stable while marketing landings keep being added -- an
# allow-list would silently drop each new SEO landing out of the funnel.
# Survey pages matter most: their impressions are our customers' respondents finding
# their own survey, traffic that can never convert into a registration.
ACQUISITION_NON_MARKETING_PREFIXES = (
    '/surveys/', '/accounts/', '/admin/', '/editor/', '/org/', '/invitations/',
    '/internal/', '/nl/', '/i18n/', '/media/', '/static/', '/staticfiles/',
    '/__debug__/',
)
# A configured source that has not synced successfully within this many hours is stale.
ACQUISITION_STALE_HOURS = int(os.environ.get('ACQUISITION_STALE_HOURS', 48))

# Landing page
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'konuchovartem@mapsurvey.org')
CONTACT_TELEGRAM = os.environ.get('CONTACT_TELEGRAM', 'Konuchovartem')
GITHUB_REPO_URL = os.environ.get('GITHUB_REPO_URL', 'https://github.com/ganjasan/mapsurvey')
DEMO_SURVEY_URL = os.environ.get('DEMO_SURVEY_URL', '')
DISCORD_INVITE_URL = os.environ.get('DISCORD_INVITE_URL', 'https://discord.gg/v6YYw3zjKH')

# Mobile-adaptive layout kill switches (openspec: mobile-adaptive-refactor).
# ON by default (owner decision at PR time). Setting the env var to False
# serves the pre-change layout on all viewports, so a bad rollout is reverted
# by flipping the env var -- no deploy rollback needed.
MOBILE_EDITOR_NAV = os.environ.get('MOBILE_EDITOR_NAV', 'True').lower() in ('true', '1')
# Autosave replaces the explicit Save button on question edit forms (all viewports —
# the one intentional desktop change of the refactor). Separate switch so desktop
# autosave can be rolled back without touching the mobile navigation.
EDITOR_AUTOSAVE = os.environ.get('EDITOR_AUTOSAVE', 'True').lower() in ('true', '1')
# Reference overlay layers on the respondent map (openspec: reference-overlay-layers).
# Off: editor UI and section checklist disappear, layer endpoints 404, respondent
# pages get no layer metadata. Stored layers are untouched — the flag gates surfaces.
MAP_REFERENCE_LAYERS = os.environ.get('MAP_REFERENCE_LAYERS', 'True').lower() in ('true', '1')
# Conditional visibility rules (openspec: conditional-question-visibility).
# Off: stored rules become inert — every question/section renders for every
# respondent, no visibility purging, and the editor hides the Visibility block.
CONDITIONAL_VISIBILITY = os.environ.get('CONDITIONAL_VISIBILITY', 'True').lower() in ('true', '1')
# Steer creators toward the AI draft on the create page (openspec:
# steer-to-ai-generation): single-field brief, empty-path intercept, wizard empty
# path skipping the map step. One switch for the whole bet — False restores the
# pre-change create page without a deploy.
CREATE_STEER_AI = os.environ.get('CREATE_STEER_AI', 'True').lower() in ('true', '1')

# Respondent file uploads (openspec: respondent-file-uploads): photo/audio/document
# question types, the async upload endpoint, and voice recording. Off: the picker
# hides the Files group, the upload endpoint answers 404, and stored file questions
# render nothing for respondents while the rest of the section keeps working.
# Stored files stay readable to creators either way.
FILE_UPLOAD_QUESTIONS = os.environ.get('FILE_UPLOAD_QUESTIONS', 'True').lower() in ('true', '1')

# Responses v2 (openspec: responses-v2-refactor): flat pane set with an Overview
# default, detail drawer, global filter pills. ON by default (owner decision,
# 2026-08-28, after six review rounds on the dev stand). Setting the env var to
# False serves the pre-change Responses template unchanged — the rollback story.
RESPONSES_V2 = os.environ.get('RESPONSES_V2', 'True').lower() in ('true', '1')

# Public results sharing
# Creators share results by copying the editor URL out of the address bar, which is the
# editor-only preview URL rather than `/r/<slug>/`. When a visitor without editor rights
# follows such a link and the results page is published, forward them there instead of
# denying the request -- otherwise the login wall turns the creator's audience into
# registrations that never wanted an account. Kill switch: set to False to restore the
# previous deny-only behaviour from the Render dashboard, without a deploy.
PUBLIC_RESULTS_PREVIEW_FALLBACK = os.environ.get(
    'PUBLIC_RESULTS_PREVIEW_FALLBACK', 'True').lower() in ('true', '1')

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'

# Newsletter
NEWSLETTER_SITE_URL = os.environ.get('NEWSLETTER_SITE_URL', 'https://mapsurvey.org')
NEWSLETTER_PHYSICAL_ADDRESS = os.environ.get(
    'NEWSLETTER_PHYSICAL_ADDRESS',
    'Kyrgyzstan, Bishkek, 11 mkr., d. 14, kv. 53, 720049'
)

# Redis cache (rate limiting). Reuses the existing mapsurvey-redis service
# on Render (DB 1; Celery uses DB 0).
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
    },
}
# When the cache backend is unreachable, allow registrations through rather
# than locking everyone out. Honeypot + Turnstile remain in effect.
DJANGO_REDIS_IGNORE_EXCEPTIONS = True
RATELIMIT_FAIL_OPEN = True

# Abuse prevention — Cloudflare Turnstile + per-IP rate limit + honeypot
# on /accounts/register/. See openspec/changes/add-registration-abuse-defenses/.
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')
# When True, trust HTTP_CF_CONNECTING_IP for client IP (production behind
# Cloudflare). Default False for local dev where the header is spoofable.
CLOUDFLARE_TRUSTED = os.environ.get('CLOUDFLARE_TRUSTED', 'False').lower() in ('true', '1')
REGISTRATION_RATE_LIMIT_HOUR = int(os.environ.get('REGISTRATION_RATE_LIMIT_HOUR', 3))
REGISTRATION_RATE_LIMIT_DAY = int(os.environ.get('REGISTRATION_RATE_LIMIT_DAY', 10))
# Attempts rejected by form validation are counted separately and far more
# loosely. A human mistyping a password three times is indistinguishable, to a
# counter that runs before validation, from a bot posting three registrations —
# and on 2026-08-17 that cost us a real signup (six POSTs, three 429s, no
# account, no email, no trace). These ceilings exist only to stop the endpoint
# being used as an unmetered password-validator oracle; nobody legitimate should
# ever reach them.
REGISTRATION_INVALID_LIMIT_HOUR = int(os.environ.get('REGISTRATION_INVALID_LIMIT_HOUR', 15))
REGISTRATION_INVALID_LIMIT_DAY = int(os.environ.get('REGISTRATION_INVALID_LIMIT_DAY', 50))
# Kill switch. False restores the pre-2026-08-17 behaviour where every POST,
# valid or not, counts against REGISTRATION_RATE_LIMIT_*. Merges reach prod in
# minutes with no staging gate, so this is the rollback.
REGISTRATION_SPLIT_RATE_LIMIT = os.environ.get(
    'REGISTRATION_SPLIT_RATE_LIMIT', 'True'
).lower() in ('true', '1')
# Resend-activation endpoint. Tighter than registration: it emails an address
# the sender does not have to control, so it is the more attractive bombing
# vector of the two. Per-IP hourly + per-email daily.
RESEND_ACTIVATION_RATE_LIMIT_HOUR = int(os.environ.get('RESEND_ACTIVATION_RATE_LIMIT_HOUR', 3))
RESEND_ACTIVATION_RATE_LIMIT_DAY = int(os.environ.get('RESEND_ACTIVATION_RATE_LIMIT_DAY', 3))

# AI survey draft generation (survey/ai/). Optional: an unset provider credential
# means the AI panel on the create page simply does not render — never a crash,
# same convention as GSC/Plausible/Turnstile above. Calls run in the Celery
# worker, so the request path never blocks on a model. Provider access goes
# through survey/ai/client.py's LLMProvider interface; 'anthropic' is the only
# implementation today (EU-hosted/local providers plug in as one class later).
# `or <default>` rather than a get() default throughout: render.yaml declares
# these as `sync: false`, and a variable left blank in the Render dashboard
# reaches the process as an empty string, which a get() default never replaces.
# An empty model name fails every generation with the provider's own 404.
AI_PROVIDER = os.environ.get('AI_PROVIDER') or 'anthropic'
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_SURVEY_DRAFT_MODEL = os.environ.get('AI_SURVEY_DRAFT_MODEL') or 'claude-opus-5'
AI_REQUEST_TIMEOUT_SECONDS = int(os.environ.get('AI_REQUEST_TIMEOUT_SECONDS') or 120)
# Google AI Studio, used with AI_PROVIDER=gemini. Its free tier is what makes
# end-to-end testing possible without a funded account; the model name is an
# env var because Google retires and renames these faster than we deploy.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
# Note: a model can appear in ListModels and still 404 on generateContent —
# Google closes older models to new keys while keeping them listed for existing
# ones (gemini-2.5-flash did exactly that). The provider surfaces the API's own
# explanation so this is diagnosable without reading Google's changelog.
GEMINI_MODEL = os.environ.get('GEMINI_MODEL') or 'gemini-3.6-flash'
# How hard the model is asked to think before answering: `minimal`, `low`,
# `medium` or `high`. Defaults to `medium` because that is already what Gemini 3
# models do when the field is absent -- introducing the setting must not change
# generation quality while we are measuring what the time is spent on. Turning
# it down is the experiment this setting exists to enable, made against data
# rather than guessed here.
#
# Empty string sends no thinkingConfig at all, which is the escape hatch if a
# future model rejects the field: a dashboard edit, not a deploy. Sent only by
# the Gemini provider; Anthropic has its own reasoning controls and ignores it.
#
# Deliberately `get(..., default)` and NOT the `or` pattern used above: here a
# blank value is a meaningful instruction ("send no thinkingConfig"), so `or`
# would swallow the very escape hatch this setting provides.
AI_THINKING_LEVEL = os.environ.get('AI_THINKING_LEVEL', 'medium')
# How long a stream may go silent before the call is abandoned as stalled.
# Needed because `requests` applies its read timeout BETWEEN chunks when
# streaming, so AI_REQUEST_TIMEOUT_SECONDS alone cannot bound a streamed call:
# a trickle of keep-alives resets the clock forever. This is the gap limit; the
# total budget below is enforced separately in the client loop. 2026-08-17's
# production stall sat quiet for 4+ minutes until Celery's soft limit killed the
# task -- with this, the same stream dies as a retryable error instead.
#
# 15, down from the initial 30, calibrated from a 10-run batch on the stand:
# every healthy stream delivered its first chunk within 2-7 seconds, while 9 of
# 19 provider calls stalled outright — so 15s of silence is almost certainly a
# dead stream, and each stall burned is a stall the creator waits through. The
# cut took the observed worst case from ~78s toward ~48s. Lower ONLY against
# fresh first-chunk data: at medium thinking the pre-first-chunk silence is
# legitimately long, and a limit under it would kill healthy streams.
AI_STREAM_STALL_SECONDS = int(os.environ.get('AI_STREAM_STALL_SECONDS') or 15)
# Streamed generation, OFF by default. On = the creator sees a progress counter
# while the draft is written; off = one blocking call, exactly as before the
# streaming change, with no progress and nothing else different.
#
# Default flipped to off on 2026-08-17 after streaming broke production twice in
# one hour: first a stream that ended without a finish reason (surfaced as
# "Couldn't reach the AI service"), then a stream that stalled after one
# question and ran until Celery's 300s soft limit killed it. Both are failure
# modes the blocking call does not have, and neither showed up in tests written
# against a well-behaved fake.
#
# Turning it back on is a dashboard edit, and the bar for doing so is evidence
# from a preview environment that a stalled or truncated stream now ends in a
# bounded, retryable error rather than a five-minute spinner.
AI_STREAMING_ENABLED = os.environ.get('AI_STREAMING_ENABLED', 'false').lower() == 'true'

LOGGING = {
    # The `abuse` logger keeps its dedicated routing (survey/abuse.py). The root
    # ('') logger sends everything else at WARNING+ to stdout so it reaches
    # Render logs — most importantly django.request's 500 tracebacks, which
    # Django's default config only emails to ADMINS (unset here), leaving
    # production errors invisible.
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'abuse': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'abuse',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'abuse': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
