# Generated by Django 2.2 on 2019-04-05 12:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_name', models.CharField(default='survey', max_length=50)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('code', models.CharField(default='blank_question', max_length=50, unique=True)),
                ('map_position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zoom', models.IntegerField(default=12)),
                ('title', models.CharField(default='Blank Question', max_length=50)),
                ('description', models.TextField(default='Blank Question')),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_next_question', to='survey.Question')),
                ('prev_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_prev_question', to='survey.Question')),
                ('survey', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
    ]
