# Generated by Django 2.2 on 2019-04-09 15:38

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=45)),
                ('sort_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('subtext', models.CharField(blank=True, max_length=500, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('radio', 'Multiple Choices'), ('checbox', 'Checkboxes'), ('rating', 'Rating'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon')], max_length=80)),
                ('option_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.OptionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('redirect_url', models.CharField(default='#', max_length=250)),
                ('start_map_postion', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('start_map_zoom', models.IntegerField(default=12)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('name', models.CharField(default='main_section', max_length=45)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('subheading', models.CharField(blank=True, max_length=4096, null=True)),
                ('code', models.CharField(max_length=8)),
                ('start_map_postion', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('start_map_zoom', models.IntegerField(default=12)),
                ('survey_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyHeader')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.OptionChoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveySection'),
        ),
        migrations.AddField(
            model_name='optionchoice',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.OptionGroup'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('yn', models.BooleanField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
                ('question_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionOption')),
                ('survey_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveySession')),
            ],
        ),
    ]
