# Generated by Django 2.2 on 2019-04-07 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190405_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='map_position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='survey',
            name='zoom',
            field=models.IntegerField(default=12),
        ),
    ]
