# Generated by Django 2.2 on 2019-04-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveysession_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='next_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_next_section', to='survey.SurveySection'),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='prev_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_prev_section', to='survey.SurveySection'),
        ),
    ]
