# Generated by Django 2.2 on 2019-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190409_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionchoice',
            old_name='sort_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='optionchoice',
            old_name='choice_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_option',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(to='survey.OptionChoice'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='choices',
            field=models.ManyToManyField(to='survey.OptionChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('rating', 'Rating'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon')], max_length=80),
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
