# Generated by Django 2.2 on 2019-04-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190407_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.CharField(default='No author', max_length=250),
        ),
        migrations.AddField(
            model_name='survey',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_first_question', to='survey.Question'),
        ),
    ]
