# Generated by Django 2.2 on 2019-04-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190411_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiongroup',
            name='choices',
        ),
    ]
