# Generated by Django 2.2 on 2019-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_optiongroup_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color',
            field=models.CharField(default='#F1F1F1', help_text='HEX color, as #RRGGBB', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='optionchoice',
            name='code',
            field=models.IntegerField(),
        ),
    ]
