# Generated by Django 2.2 on 2019-09-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190508_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_answer_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
