# Generated by Django 2.2 on 2019-04-08 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='session_start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
