# Generated by Django 2.2 on 2019-04-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190408_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveySession'),
            preserve_default=False,
        ),
    ]
