# Generated by Django 2.2 on 2019-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190926_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='color',
            field=models.CharField(default='#000000', help_text='HEX color, as #RRGGBB', max_length=7, verbose_name='Color'),
        ),
    ]
