# Generated by Django 2.2 on 2019-10-08 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20191003_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyheader',
            name='name',
            field=models.CharField(max_length=45, unique=True, validators=[survey.models.validate_url_name]),
        ),
        migrations.AlterField(
            model_name='surveyheader',
            name='start_map_postion',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(30.317 59.945)', srid=4326),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='name',
            field=models.CharField(default='survey_description', max_length=45, validators=[survey.models.validate_url_name]),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='start_map_postion',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(30.317 59.945)', srid=4326),
        ),
    ]
