# Generated by Django 2.2 on 2019-04-08 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190408_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='answer',
            name='numeric',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='yn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
