# Generated by Django 2.2 on 2019-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20191008_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyheader',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='surveyheader',
            name='start_map_postion',
        ),
        migrations.RemoveField(
            model_name='surveyheader',
            name='start_map_zoom',
        ),
        migrations.RemoveField(
            model_name='surveyheader',
            name='title',
        ),
    ]
