# Generated by Django 2.2 on 2019-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20191008_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon_class',
            field=models.CharField(default='', help_text='Must be Font-Awesome class', max_length=80),
        ),
    ]
