# Generated by Django 2.2 on 2019-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_question_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='icon_class',
            field=models.CharField(blank=True, default='', help_text='Must be Font-Awesome class', max_length=80, null=True),
        ),
    ]
