# Generated by Django 2.2 on 2019-10-14 17:12

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20191014_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(default=survey.models.question_code_generator, max_length=12),
        ),
    ]
