# Generated by Django 4.2.27 on 2026-04-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_validation_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('alternative', 'Alternative'), ('vs', 'Vs'), ('migrate', 'Migrate')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('last_fact_checked', models.DateField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_pages', to='survey.competitor')),
            ],
            options={
                'ordering': ['competitor', 'page_type'],
                'unique_together': {('competitor', 'page_type')},
            },
        ),
    ]
