# Generated by Django 4.2.27 on 2026-04-14 06:02

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_validation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='basemaps',
            field=models.JSONField(blank=True, default=survey.models.default_basemaps, help_text='Enabled basemaps for respondent map. List from: ["streets", "satellite", "topo"]'),
        ),
        migrations.RunPython(
            lambda apps, se: apps.get_model('survey', 'SurveyHeader').objects.filter(basemaps=[]).update(basemaps=['streets', 'satellite', 'topo']),
            migrations.RunPython.noop,
        ),
    ]
