# Generated by Django 4.2.27 on 2026-04-14 08:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_populate_default_basemaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='default_basemap',
            field=models.CharField(blank=True, choices=[('streets', 'Streets'), ('satellite', 'Satellite'), ('topo', 'Topo')], help_text='Default basemap shown to respondents. If null, first from basemaps list.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='start_map_postion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Default map position for the survey. Sections inherit this if not overridden.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='start_map_zoom',
            field=models.IntegerField(blank=True, help_text='Default map zoom for the survey. Sections inherit this if not overridden.', null=True),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='override_basemap',
            field=models.CharField(blank=True, choices=[('streets', 'Streets'), ('satellite', 'Satellite'), ('topo', 'Topo')], help_text='Override basemap for this section. Null = keep current basemap.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='start_map_postion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Override map position for this section. Null = keep current map position.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='start_map_zoom',
            field=models.IntegerField(blank=True, help_text='Override map zoom for this section. Null = keep current zoom.', null=True),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='use_geolocation',
            field=models.BooleanField(default=False, help_text='If true, fly to respondent location when entering this section.'),
        ),
    ]
