# Generated by Django 4.2.27 on 2026-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_persistent_map_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='use_geolocation',
            field=models.BooleanField(default=False, help_text='Auto-center map on respondent location when entering the survey.'),
        ),
    ]
