# Generated by Django 4.2.27 on 2026-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_surveyheader_use_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense', models.CharField(choices=[('captcha', 'Turnstile CAPTCHA'), ('ratelimit', 'Rate Limit'), ('honeypot', 'Honeypot'), ('email_domain', 'Disposable Email Domain')], db_index=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
