# Generated by Django 4.2.27 on 2026-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_abuseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelReport',
            fields=[
            ],
            options={
                'verbose_name': 'Funnel dashboard',
                'verbose_name_plural': 'Funnel dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('survey.surveyheader',),
        ),
    ]
