# Generated by Django 4.2.27 on 2026-06-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_abuseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicResultsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], default='public', help_text='Public is indexable and listable; unlisted is reachable by direct link only.', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('intro', models.JSONField(blank=True, default=dict, help_text='Multilingual intro: {"title": {"en": ...}, "body": {"en": ...}} or plain strings.')),
                ('mode', models.CharField(choices=[('live', 'Live'), ('frozen', 'Frozen')], default='live', max_length=10)),
                ('snapshot', models.JSONField(blank=True, help_text='Frozen per-block payloads.', null=True)),
                ('snapshot_version', models.PositiveIntegerField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('show_response_count', models.BooleanField(default=True)),
                ('show_participate_cta', models.BooleanField(default=True)),
                ('feature_in_listing', models.BooleanField(default=False, help_text='Show a card in the public stories listing (public visibility only).')),
                ('k_anonymity_threshold', models.PositiveIntegerField(default=3, help_text='Mask buckets with 0 < count < K as "<K". Set to 1 to disable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_results_page', to='survey.surveyheader')),
            ],
        ),
        migrations.CreateModel(
            name='PublicResultsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('chart', 'Chart'), ('map', 'Map')], max_length=10)),
                ('viz', models.CharField(default='auto', help_text='Visualization override: auto, bar, pie, donut, table, heatmap, ...', max_length=20)),
                ('custom_title', models.JSONField(blank=True, default=dict, help_text='Optional multilingual title override.')),
                ('geo_label_fields', models.JSONField(blank=True, default=list, help_text='Question codes whose values appear in geo popups. Empty = anonymous geometry only.')),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='survey.publicresultspage')),
                ('question', models.ForeignKey(blank=True, help_text='Bound question for chart/map blocks; null for text.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
