# Generated by Django 4.2.27 on 2026-07-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0032_funnelreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_referrer', models.CharField(blank=True, max_length=512)),
                ('source_bucket', models.CharField(blank=True, max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_attribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
