# Generated by Django 4.2.27 on 2026-07-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_signupattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='show_branding',
            field=models.BooleanField(default=True, help_text='Show a "Made with Mapsurvey" link on the public survey and thanks pages (a free-tier acquisition loop). Turn off for a clean, unbranded look.'),
        ),
    ]
