# Generated by Django 4.2.27 on 2026-07-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_publicresultsblock_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicresultsblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for standalone image blocks.', null=True, upload_to='public_results_blocks/'),
        ),
        migrations.AlterField(
            model_name='publicresultsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('chart', 'Chart'), ('map', 'Map')], max_length=10),
        ),
        migrations.AlterField(
            model_name='publicresultsblock',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual body for standalone text blocks, or caption for image blocks: {"en": "...", "ru": "..."}.'),
        ),
        migrations.AlterField(
            model_name='publicresultsblock',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Bound question for chart/map blocks; null for text/image.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question'),
        ),
    ]
