# Generated by Django 4.2.27 on 2026-07-23 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0034_surveyheader_show_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the survey is moved to trash; purged permanently after the retention window.', null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('survey_trash', 'Survey moved to trash'), ('survey_restore', 'Survey restored from trash'), ('survey_purge', 'Survey permanently deleted'), ('survey_auto_purge', 'Survey auto-purged after retention'), ('status_transition', 'Lifecycle status transition'), ('clear_test_data', 'Test sessions cleared'), ('draft_publish', 'Draft published as new version'), ('draft_discard', 'Draft discarded'), ('password_set', 'Survey password set'), ('password_remove', 'Survey password removed'), ('token_regenerate', 'Test token regenerated')], db_index=True, max_length=30)),
                ('survey_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('survey_name', models.CharField(blank=True, default='', max_length=45)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
