# Generated by Django 4.2.27 on 2026-07-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_surveyheader_deleted_at_auditlog'),
        ('survey', '0035_useractivity'),
    ]

    operations = [
    ]
