# Generated by Django 4.2.27 on 2026-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_merge_20260723_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_style',
            field=models.CharField(choices=[('default', 'Survey default'), ('scale_strip', 'Compact scale'), ('list_pips', 'Labeled list')], default='default', help_text='Rendering style, only used by rating questions; "default" inherits the survey-wide style', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='style_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Survey-wide style defaults: {rating_display_style}'),
        ),
    ]
