# Generated by Django 4.2.27 on 2026-07-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0037_question_display_style_surveyheader_style_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Hex colour used on the funnel dashboard, e.g. #3b82f6.', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('dimension__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CohortDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto', 'Automatic rule'), ('manual', 'Staff assignment')], default='manual', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='survey.cohort')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='survey.cohortdimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='survey.cohortdimension'),
        ),
        migrations.AddConstraint(
            model_name='usercohort',
            constraint=models.UniqueConstraint(fields=('user', 'dimension'), name='unique_user_cohort_per_dimension'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('dimension', 'slug'), name='unique_cohort_slug_per_dimension'),
        ),
    ]
