# Generated by Django 4.2.27 on 2026-07-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0039_seed_cohorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('how_found_us', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Short markdown summary: who this is, in a few lines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('research', 'Research'), ('email', 'Email'), ('call', 'Call'), ('signal', 'Signal')], default='research', max_length=10)),
                ('happened_on', models.DateField()),
                ('body', models.TextField()),
                ('source_path', models.CharField(blank=True, db_index=True, help_text='Repo-relative path this note was imported from, if any.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_creator_notes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-happened_on', '-id'),
                'indexes': [models.Index(fields=['user', 'happened_on'], name='survey_crea_user_id_5187f5_idx')],
            },
        ),
    ]
