# Generated by Django 4.2.27 on 2026-07-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_creator_dossiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSegmentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rules', to='survey.cohort')),
            ],
            options={
                'ordering': ('domain',),
            },
        ),
    ]
