# Generated by Django 4.2.27 on 2026-07-30 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0041_domain_segment_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSyncState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gsc', 'Google Search Console'), ('plausible', 'Plausible')], max_length=20, unique=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('source',),
            },
        ),
        migrations.CreateModel(
            name='DemoOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_open', to='survey.surveysession')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the demo was opened by a signed-in user; NULL = anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AcquisitionDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gsc', 'Google Search Console'), ('plausible', 'Plausible')], max_length=20)),
                ('date', models.DateField()),
                ('segment', models.CharField(blank=True, default='', help_text='Slice within the source; meaning depends on the source.', max_length=60)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
                ('visitors', models.IntegerField(blank=True, null=True)),
                ('pageviews', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date', 'source', 'segment'),
                'indexes': [models.Index(fields=['source', 'date'], name='survey_acqu_source_965125_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acquisitiondaily',
            constraint=models.UniqueConstraint(fields=('source', 'date', 'segment'), name='unique_acquisition_daily'),
        ),
    ]
