# Generated by Django 4.2.27 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_publicresultspage_publicresultsblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicresultsblock',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual body for standalone text blocks: {"en": "...", "ru": "..."}.'),
        ),
    ]
