# Generated by Django 4.2.27 on 2026-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_publicresultsblock_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicresultsblock',
            name='basemap',
            field=models.CharField(choices=[('streets', 'Streets'), ('satellite', 'Satellite'), ('topo', 'Topo')], default='streets', help_text='Tile basemap for map blocks (streets/satellite/topo).', max_length=20),
        ),
    ]
