# Generated by Django 4.2.27 on 2026-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_publicresultsblock_basemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicresultspage',
            name='show_on_thanks',
            field=models.BooleanField(default=True, help_text='Show a "See the results" button on the survey\'s thanks page (only while published).'),
        ),
    ]
