# Generated by Django 4.2.27 on 2026-08-14 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0047_publicresultspage_show_on_thanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('survey_draft', 'Survey draft generation')], db_index=True, max_length=30)),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('not_configured', 'Provider not configured'), ('provider_error', 'Provider error'), ('invalid_draft', 'Invalid draft'), ('error', 'Unexpected error')], db_index=True, default='pending', max_length=20)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('generated_blob', models.JSONField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('redirected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_events', to='survey.surveyheader')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_events', to='survey.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
