# Generated by Django 4.2.27 on 2026-08-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_ai_generation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationevent',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aigenerationevent',
            name='thinking_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aigenerationevent',
            name='total_latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
    # `makemigrations` also proposes two choices-only AlterFields on `question`
    # (input_type gaining 'ranking', display_style's rating styles). Those are
    # pre-existing drift from 99cca4c and are deliberately NOT folded in here:
    # they are nobody's schema change (choices are a no-op at the DB level) and
    # reverting this migration must not revert another change's model state.
