# Generated by Django 4.2.27 on 2026-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_ai_generation_latency_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationevent',
            name='sections_drafted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aigenerationevent',
            name='questions_drafted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
    # As in 0049: `makemigrations` also proposes two choices-only AlterFields on
    # `question`. They are pre-existing drift from 99cca4c (the ranking-question
    # change) and are not this migration's to carry — reverting the draft
    # counters must not revert another change's model state.
