# Generated by Django 4.2.27 on 2026-08-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_ai_generation_draft_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='display_style',
            field=models.CharField(choices=[('default', 'Survey default'), ('scale_strip', 'Compact scale'), ('list_pips', 'Labeled list'), ('stars', 'Stars')], default='default', help_text='Rendering style, only used by rating questions; "default" inherits the survey-wide style', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('range', 'Range'), ('rating', 'Rating'), ('ranking', 'Ranking'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon'), ('image', 'Image'), ('text_line', 'Single Line Text'), ('html', 'HTML')], max_length=80),
        ),
    ]
