# Generated by Django 4.2.27 on 2026-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0052_fold_primary_language_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='display_style',
            field=models.CharField(choices=[('default', 'Survey default'), ('scale_strip', 'Compact scale'), ('list_pips', 'Labeled list'), ('stars', 'Stars'), ('dropdown', 'Dropdown with search')], default='default', help_text='Rendering style: rating styles ("default" inherits the survey-wide style) or "dropdown" for choice questions', max_length=20),
        ),
    ]
