# Generated by Django 4.2.27 on 2026-08-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_choice_dropdown_display_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='subtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
