# Generated by Django 4.2.27 on 2026-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0053_formatted_text_body_unbounded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysection',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveysectiontranslation',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
