# Generated by Django 4.2.27 on 2026-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0056_escape_legacy_plain_text_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='layout',
            field=models.CharField(choices=[('map', 'Map'), ('form', 'Form')], default='map', help_text='"map" renders the panel beside the map; "form" renders a classic full-width form with no map', max_length=8),
        ),
    ]
