# Generated by Django 4.2.27 on 2026-08-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0057_section_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='next_label',
            field=models.CharField(blank=True, help_text='Custom label for the forward button, e.g. "Start" on a welcome section. Empty = the default Next/Finish.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='surveysectiontranslation',
            name='next_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
