# Generated by Django 4.2.27 on 2026-08-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_clear_choices_on_nonchoice_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='hidden_layers',
            field=models.JSONField(blank=True, default=list, help_text='IDs of SurveyMapLayer rows hidden on this section. Empty = all layers visible. Stale IDs are ignored at render time.'),
        ),
        migrations.CreateModel(
            name='SurveyMapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#2c7be5', help_text='Fallback style; simplestyle properties inside the file win.', max_length=7)),
                ('label_field', models.CharField(blank=True, default='', help_text='Feature property rendered as a permanent map label. Empty = no labels.', max_length=100)),
                ('key_field', models.CharField(blank=True, default='', help_text='Feature property that makes features addressable (reserved for answer-driven map context). No UI consumer yet.', max_length=100)),
                ('show_popups', models.BooleanField(default=False, help_text='Tap a feature shows a read-only popup of its name/description properties.')),
                ('geojson', models.TextField(help_text='Re-serialized FeatureCollection — never the raw uploaded bytes.')),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='survey.surveyheader')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
