# Generated by Django 4.2.27 on 2026-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_surveysection_hidden_layers_surveymaplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visibility_rule',
            field=models.JSONField(blank=True, help_text="Show this question only when the referenced choice question's answer includes any of the referenced option codes. Null = always shown.", null=True),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='visibility_rule',
            field=models.JSONField(blank=True, help_text="Show this section only when the referenced choice question's answer includes any of the referenced option codes. Null = always shown.", null=True),
        ),
    ]
