# Generated by Django 4.2.27 on 2026-08-27 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import survey.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0062_visibility_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('range', 'Range'), ('rating', 'Rating'), ('ranking', 'Ranking'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon'), ('image', 'Image'), ('text_line', 'Single Line Text'), ('html', 'HTML'), ('photo', 'Photo Upload'), ('audio', 'Audio Upload'), ('document', 'Document Upload')], max_length=80),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, storage=survey.models._private_media_storage, upload_to=survey.models.upload_key)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='survey.surveysession')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.upload'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['attached', 'created_at'], name='survey_uplo_attache_fe61c0_idx'),
        ),
    ]
