# Generated by Django 4.2.27 on 2026-08-29 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0064_creatorpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, default='', max_length=200)),
                ('segment', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('missing_text', models.TextField(blank=True, default='')),
                ('budget_shape', models.CharField(blank=True, default='', max_length=32)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
