# Generated by Django 4.2.27 on 2026-09-01 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_merge_slug_repair_and_pro_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Creator rich text — passes html_sanitize on every write.')),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('position', models.PositiveIntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='geojson_legacy',
            field=models.TextField(blank=True, default='', help_text='The pre-objects FeatureCollection kept for one release after the split migration; empty for layers created since.'),
        ),
        migrations.AlterField(
            model_name='surveymaplayer',
            name='geojson',
            field=models.TextField(help_text='Derived FeatureCollection, rebuilt from the layer objects on every write.'),
        ),
        migrations.AlterField(
            model_name='surveymaplayer',
            name='key_field',
            field=models.CharField(blank=True, default='', help_text='Feature property used as the object key on import. Answers about objects are stored against the key.', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveymaplayer',
            name='label_field',
            field=models.CharField(blank=True, default='', help_text='Feature property rendered as a permanent map label. Empty = no labels. Also the default title mapping for imports.', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveymaplayer',
            name='show_popups',
            field=models.BooleanField(default=False, help_text='Tap a feature shows a read-only popup of its title/description (layers not bound to an Objects-on-the-map question).'),
        ),
        migrations.CreateModel(
            name='LayerObjectAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('document', 'Document'), ('video', 'Video'), ('embed', 'Embedded video')], max_length=10)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=survey.models.layer_asset_key)),
                ('embed_url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='survey.layerobject')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='layerobject',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='survey.surveymaplayer'),
        ),
        migrations.AddIndex(
            model_name='layerobject',
            index=models.Index(fields=['layer', 'category'], name='survey_laye_layer_i_d0f090_idx'),
        ),
        migrations.AddConstraint(
            model_name='layerobject',
            constraint=models.UniqueConstraint(fields=('layer', 'key'), name='layerobject_unique_key_per_layer'),
        ),
    ]
