# Generated by Django 4.2.27 on 2026-09-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0068_split_layers_into_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.surveymaplayer'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_objects',
            field=models.PositiveIntegerField(default=0, help_text='`layer_objects` only: the respondent must answer about at least this many objects to move on. 0 = optional. Replaces `required` for this type.'),
        ),
        migrations.AddField(
            model_name='question',
            name='objects_search',
            field=models.CharField(choices=[('auto', 'Automatic — shown for more than 5 objects or when categories exist'), ('on', 'Always'), ('off', 'Never')], default='auto', help_text='`layer_objects` only: whether the list shows a search box and category chips.', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('range', 'Range'), ('rating', 'Rating'), ('ranking', 'Ranking'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon'), ('image', 'Image'), ('text_line', 'Single Line Text'), ('html', 'HTML'), ('photo', 'Photo Upload'), ('audio', 'Audio Upload'), ('document', 'Document Upload'), ('thumbs', 'Thumbs up / down'), ('layer_objects', 'Objects on the map')], max_length=80),
        ),
    ]
