# Generated by Django 4.2.27 on 2026-09-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0069_question_layer_objects_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='layer_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.layerobject'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('layer_object__isnull', False)), fields=('survey_session', 'question', 'layer_object'), name='answer_unique_per_session_question_object'),
        ),
    ]
