# Generated by Django 4.2.27 on 2026-09-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0071_public_results_objects_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layerobject',
            name='source_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.answer'),
        ),
        migrations.AddField(
            model_name='layerobject',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_objects', to='survey.surveysession'),
        ),
        migrations.AddField(
            model_name='layerobject',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('pending', 'pending'), ('hidden', 'hidden')], default='visible', max_length=8),
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='approve_first',
            field=models.BooleanField(default=False, help_text='`question` layers only: new marks wait as `pending` until the creator approves them.'),
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='show_comments',
            field=models.BooleanField(default=False, help_text="`question` layers only: respondents see other people's comments on a mark."),
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='show_tallies',
            field=models.BooleanField(default=True, help_text="`question` layers only: respondents see 👍/👎 counts on other people's marks."),
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='source',
            field=models.CharField(choices=[('upload', 'upload'), ('question', 'question')], default='upload', max_length=8),
        ),
        migrations.AddField(
            model_name='surveymaplayer',
            name='source_question_code',
            field=models.CharField(blank=True, default='', help_text='`question` layers only: code of the point/line/polygon question whose answers become the objects.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='layerobject',
            index=models.Index(fields=['layer', 'status'], name='survey_laye_layer_i_430ced_idx'),
        ),
    ]
