# Generated by Django 4.2.27 on 2026-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0072_shared_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymaplayer',
            name='style',
            field=models.JSONField(blank=True, default=dict, help_text='Base style (opacity, weight, fill_opacity, radius, icon) and an optional rule `by` one object property; normalised on every write.'),
        ),
    ]
