# Generated by Django 4.2.27 on 2026-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0077_backfill_marks_and_legend_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupattribution',
            name='landing_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
