# Generated by Django 4.2.27 on 2026-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0078_signupattribution_landing_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='opened_by_kind',
            field=models.CharField(choices=[('external', 'external'), ('owner', 'owner'), ('collaborator', 'collaborator'), ('preview', 'preview')], default='external', max_length=12),
        ),
    ]
