# Generated by Django 4.2.27 on 2026-09-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0079_surveysession_opened_by_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcquisitionDaily',
        ),
        migrations.DeleteModel(
            name='AcquisitionSyncState',
        ),
    ]
