# Generated by Django 4.2.27 on 2026-09-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0080_drop_acquisition_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_kind', models.CharField(choices=[('question', 'Question'), ('section', 'Section'), ('session', 'Response'), ('block', 'Public results block')], max_length=10)),
                ('question_code', models.CharField(blank=True, default='', max_length=50)),
                ('section_code', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='survey.publicresultsblock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='survey.surveysession')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='survey.surveyheader')),
            ],
            options={
                'ordering': ['-last_activity_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File')], max_length=5)),
                ('file', models.FileField(max_length=500, storage=survey.models._private_media_storage, upload_to=survey.models.comment_attachment_key)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='survey.comment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='survey.commentthread'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['survey', 'status', 'anchor_kind'], name='survey_comm_survey__c4c6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['survey', 'question_code'], name='survey_comm_survey__5f88aa_idx'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['survey', 'section_code'], name='survey_comm_survey__d22fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentthread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anchor_kind', 'question'), ('block__isnull', True), ('section_code', ''), ('session__isnull', True), models.Q(('question_code', ''), _negated=True)), models.Q(('anchor_kind', 'section'), ('block__isnull', True), ('question_code', ''), ('session__isnull', True), models.Q(('section_code', ''), _negated=True)), models.Q(('anchor_kind', 'session'), ('block__isnull', True), ('question_code', ''), ('section_code', ''), ('session__isnull', False)), models.Q(('anchor_kind', 'block'), ('block__isnull', False), ('question_code', ''), ('section_code', ''), ('session__isnull', True)), _connector='OR'), name='commentthread_one_anchor_only'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'created_at'], name='survey_comm_thread__82615e_idx'),
        ),
    ]
