# Generated by Django 4.2.27 on 2026-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0082_comment_seen_and_edits'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentthread',
            name='commentthread_one_anchor_only',
        ),
        migrations.AlterField(
            model_name='commentthread',
            name='anchor_kind',
            field=models.CharField(choices=[('survey', 'Survey'), ('question', 'Question'), ('section', 'Section'), ('session', 'Response'), ('block', 'Public results block')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='commentthread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anchor_kind', 'survey'), ('block__isnull', True), ('question_code', ''), ('section_code', ''), ('session__isnull', True)), models.Q(('anchor_kind', 'question'), ('block__isnull', True), ('section_code', ''), ('session__isnull', True), models.Q(('question_code', ''), _negated=True)), models.Q(('anchor_kind', 'section'), ('block__isnull', True), ('question_code', ''), ('session__isnull', True), models.Q(('section_code', ''), _negated=True)), models.Q(('anchor_kind', 'session'), ('block__isnull', True), ('question_code', ''), ('section_code', ''), ('session__isnull', False)), models.Q(('anchor_kind', 'block'), ('block__isnull', False), ('question_code', ''), ('section_code', ''), ('session__isnull', True)), _connector='OR'), name='commentthread_one_anchor_only'),
        ),
    ]
