# Generated by Django 4.2.27 on 2026-09-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0086_surveymaplayer_geojson_gz'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='story',
            name='credit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='story',
            name='credit_logo',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='story',
            name='credit_note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='story',
            name='facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='place',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='story',
            name='sector',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='story',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('map', 'Map'), ('open-data', 'Open Data'), ('results', 'Results'), ('article', 'Article'), ('case-study', 'Case study')], default='article', max_length=20),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('image', models.ImageField(upload_to='stories/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='survey.story')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storyimage',
            constraint=models.UniqueConstraint(fields=('story', 'key'), name='story_image_key_unique'),
        ),
    ]
