# Generated by Django 4.2.27 on 2026-09-25 15:27

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0086_surveymaplayer_geojson_gz'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='basemap_mode',
            field=models.CharField(choices=[('tiles', 'Map tiles'), ('image', 'Uploaded image')], default='tiles', max_length=10),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=survey.models.image_basemap_key),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap_pending',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap_state',
            field=models.CharField(blank=True, choices=[('', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='image_basemap_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
