# Generated by Django 4.2.27 on 2026-10-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0087_story_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='credit_note_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='story',
            name='credit_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
