# Generated by Django 4.2.27 on 2026-10-02 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0090_creatorpreferences_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abuseevent',
            name='defense',
            field=models.CharField(choices=[('captcha', 'Turnstile CAPTCHA'), ('ratelimit', 'Rate Limit'), ('honeypot', 'Honeypot'), ('email_domain', 'Disposable Email Domain'), ('content_screen', 'Content screening')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('survey_trash', 'Survey moved to trash'), ('survey_restore', 'Survey restored from trash'), ('survey_purge', 'Survey permanently deleted'), ('survey_auto_purge', 'Survey auto-purged after retention'), ('status_transition', 'Lifecycle status transition'), ('clear_test_data', 'Test sessions cleared'), ('draft_publish', 'Draft published as new version'), ('draft_discard', 'Draft discarded'), ('password_set', 'Survey password set'), ('password_remove', 'Survey password removed'), ('token_regenerate', 'Test token regenerated'), ('content_screen_close', 'Survey closed after a confirmed phishing review')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ContentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Held, waiting for review'), ('reported', 'Reported by a respondent'), ('cleared', 'Released'), ('confirmed', 'Confirmed phishing')], default='pending', max_length=12)),
                ('source', models.CharField(choices=[('screen', 'Content screening'), ('report', 'Respondent report')], default='screen', max_length=8)),
                ('trigger', models.CharField(blank=True, default='', max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reviews_decided', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to='survey.surveyheader')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['survey', 'status'], name='survey_contentreview_open_idx')],
            },
        ),
    ]
