# Generated by Django 4.2.27 on 2026-10-03 20:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0091_contentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='multipoint',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='question',
            name='spray_brush',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='`spraycan` only: brush size the respondent paints with.', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('range', 'Range'), ('rating', 'Rating'), ('ranking', 'Ranking'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon'), ('spraycan', 'Spray area'), ('image', 'Image'), ('text_line', 'Single Line Text'), ('html', 'HTML'), ('photo', 'Photo Upload'), ('audio', 'Audio Upload'), ('document', 'Document Upload'), ('thumbs', 'Thumbs up / down'), ('layer_objects', 'Objects on the map')], max_length=80),
        ),
    ]
