# Generated by Django 4.2.27 on 2026-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0092_spraycan'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
